// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default FirebaseOptions for each platform.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXF15x_R_CHqDUUXKpl6LaHPKo23x2eR8',
    appId: '1:618334712369:android:1eed9d6181e9aab180db10',
    messagingSenderId: '618334712369',
    projectId: 'my-cbd-app',
    storageBucket: 'my-cbd-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdlLAK8AOdVfYdsJJv6kxNQjEXWjQasxc',
    appId: '1:618334712369:ios:6703c6ebac61515a80db10',
    messagingSenderId: '618334712369',
    projectId: 'my-cbd-app',
    storageBucket: 'my-cbd-app.appspot.com',
    iosClientId:
        '618334712369-5smjgj1bg4462itjo0mctt4v9hd8pcmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
